# Classify all HTML files by their copyright notices
# - None (no "Copyright" or "©" etc)
# - CC-BY-SA 4.0
# - All Rights Reserved
# - Other/Unknown
# As much as possible, find the exact beginning and end of the copyright
# notice, thus allowing them to be replaced as needed. But for now, just
# classify the files.
# Fixes to be done:
# * If copyright is "All Rights Reserved", simply remove that text. It is
#   now copyright="None".
# * If copyright is "None", add a <footer> at the end of document.body.main
#   or document.body, as per _layouts/default.html in the Markdown files.
#   It is now copyright="CC-BY-SA 4.0".
import os
import re
import sys
import collections
from bs4 import BeautifulSoup, Comment, Tag

# root = "/home/rosuav/gsarchive/live"
root = "/home/rosuav/gsarchive/clone" # Faster and safer, not touching the original files

copyright = re.compile(r"""
	Copyright.*
	(
		Gilbert\s*and\s*Sullivan\s*Archive
		| Paul\s*Howarth
		| Colin\s*Johnson
	)
	.*All\s*Rights\s*Reserved
""", re.IGNORECASE | re.VERBOSE | re.DOTALL)

def classify(fn):
	info = { }
	with open(fn, "rb") as f: blob = f.read()
	soup = BeautifulSoup(blob, "html.parser")
	if soup.find(text=lambda text: isinstance(text, Comment) and "autogenerated" in text.lower()):
		info["generated"] = 1
	# Okay. So, what are we looking for, exactly?
	# 1) Easy mode: an anchor rel="license".
	for tag in soup.findAll(rel="license"):
		if tag["href"] == "https://creativecommons.org/licenses/by-sa/4.0/":
			return info | {"copyright": "CC-BY-SA 4.0"}
		if tag["href"] == "http://creativecommons.org/licenses/by-sa/4.0/":
			return info | {"copyright": "CC-BY-SA 4.0"} # Maybe fix protocol? Or not bother.
		if tag["href"] == "https://creativecommons.org/publicdomain/mark/1.0/":
			return info | {"copyright": "Public Domain"} # Fix to BY-SA 4.0 in case of future edits?
		info.setdefault("links", []).append(tag["href"])
	if "links" in info:
		return info | {"copyright": "Unknown"}
	for cr in soup.findAll(text=True):
		if m := copyright.search(cr.text):
			return info | {"copyright": "All Rights Reserved"}
		# Look for any copyright marker, including a miswritten HTML entity
		if "copyright" in cr.text or "©" in cr.text or "&copy" in cr.text:
			# Maybe there's a full copyright notice in the parent's text,
			# but it's split up by HTML tags.
			if m := copyright.search(cr.parent.text):
				# Fixing this is going to be harder. But it's still an ARR
				# copyright notice.
				if "text" in info: del info["text"]
				return info | {"copyright": "All Rights Reserved", "fix": "if possible"}
			info.setdefault("text", []).append(cr.text)
	return info | {"copyright": "Unknown" if info.get("text") else "None"}

for fn in sys.argv[1:]:
	if os.path.exists(fn):
		print(classify(fn))
		sys.exit(0)

stats = collections.Counter()
with open("copywrong.log", "w") as log:
	for root, dirs, files in os.walk(root):
		for file in files:
			fn = os.path.join(root, file)
			info = classify(fn)
			stats[info["copyright"]] += 1
			if not stats.total() % 1000: print(stats.total(), stats)
			if info["copyright"] == "Unknown":
				print(fn, info, file=log)
			elif info["copyright"] not in ("All Rights Reserved", "None", "CC-BY-SA 4.0", "Public Domain"):
				print(fn, info)
print(stats.total(), stats)

""" For manual testing:
def get(fn):
    global soup, cr
    soup = BeautifulSoup(open(fn).read(), "html.parser")
    cr = soup.find(text=lambda t: "Copyright" in t.text)
"""
