#!/usr/bin/python3
import sys, subprocess
actions = ["xdotool"]
loop = 1
for arg in sys.argv[1:]:
	cmd, *args = arg.split(":")
	if cmd == "ac" or cmd == "up":
		if not args:
			print("Activate what?")
			continue
		if len(args) == 1: args = [args[0], args[0]]
		for pos in range(int(args[0]), int(args[1])+1): # inc-inc range
			actions += ["mousemove",
				str(2400 + 600 * (pos > 4) + 150 * (cmd != "ac")),
				str(325 + 150 * (pos % 5) + 50 * (cmd != "ac")),
				"click", "1",
			]
	if cmd == "power":
		actions += ["mousemove", "2400", "325", "click", "--repeat", "75", "--delay", "50", "1"]
	if cmd == "batch":
		actions += ["mousemove", "3700", "75", "click", "1"]
	if cmd == "sleep":
		actions += ["sleep", args[0] if args else "2"]
	if cmd == "loop":
		loop = int(args[0] if args else 1000000)
try:
	for _ in range(loop):
		if subprocess.run(["xdotool", "getactivewindow", "getwindowname"], capture_output=True, encoding="utf-8").stdout != "AdCap!\n":
			print("Focus is gone, halting")
			sys.exit(1)
		subprocess.run(actions)
except KeyboardInterrupt:
	print()
	sys.exit(1) # Silent, but return failure
