#!/usr/bin/python3
import sys, subprocess
if subprocess.run(["xdotool", "getactivewindow", "getwindowname"], capture_output=True, encoding="utf-8").stdout != "AdCap!\n":
	print("Focus is gone, halting")
	sys.exit(1)
actions = ["xdotool"]
for arg in sys.argv[1:]:
	cmd, *args = arg.split(":")
	if cmd == "ac" or cmd == "up":
		if not args:
			print("Activate what?")
			continue
		if len(args) == 1: args = [args[0], args[0]]
		for pos in range(int(args[0]), int(args[1])+1): # inc-inc range
			actions += ["mousemove",
				str(2400 + 600 * (pos > 4) + 150 * (cmd != "ac")),
				str(325 + 150 * (pos % 5) + 50 * (cmd != "ac")),
				"click", "1",
			]
	if cmd == "power":
		actions += ["mousemove", "2400", "325", "click", "--repeat", "75", "1"]
subprocess.run(actions)
