#!/bin/bash
# Steam autologin
# Requires https://github.com/dyc3/steamguard-cli and xdotool (probably found in your distro repos)
USERNAME=$1
PASSWORD=$2
steam &
if [ -z "$PASSWORD" ]; then
	login() {
		xdotool search --name "Steam Login" windowactivate type $USERNAME && xdotool sleep 0.1 key Tab
	}
else
	login() {
		xdotool search --name "Steam Login" windowactivate type $USERNAME && xdotool sleep 0.1 key Tab type $PASSWORD && xdotool sleep 0.1 key Return
	}
fi
xdotool search --name "Steam Guard" windowactivate || until login; do echo Waiting for Steam login window...; sleep 1; done
until xdotool search --name "Steam Guard" windowactivate && xdotool type `python3 ~/shed/steamguard.py $USERNAME` && xdotool sleep 0.1 key Return
do echo Waiting for steamguard window...; sleep 1; done
echo Logged in.
